## gen_render2d_pica.nim — regenerate shaders/render2d.v.pica from a Nim proc.
##
## SOURCE OF TRUTH for boxy's PICA200 2D vertex shader. The `render2dVert` proc
## below is compiled to picasso `.v.pica` assembly by Shady's `toPica` macro; the
## emitted file is committed to the repo as a build artifact. Edit the PROC here
## and regenerate — never hand-edit shaders/render2d.v.pica.
##
## This is a HOST tool. It is never cross-compiled for the 3DS, and boxy's
## -d:ds3 / ARM build does not depend on it: the committed .v.pica is what
## scripts/build_3ds.sh assembles. Confining `toPica` (and thus Shady) to this
## regeneration tool keeps fresh-clone and desktop builds free of any dependency
## on the unmerged Shady PICA200 branch.
##
## Prerequisites (regeneration only):
##   - Shady with `toPica` — branch `matt.spurlin/3ds-pica200-support`
##     (github.com/birbparty/shady). Released Shady does NOT have `toPica`; point
##     Nim at a branch checkout via --path. Record the exact Shady commit you
##     regenerated against in the *git commit message*, not here — a hand-edited
##     commit literal in this file would silently go stale as the branch moves.
##
## Usage (from the repo root):
##   nim r -d:shadyNoPixie --path:"$HOME/git/shady/src" \
##     tools/gen_render2d_pica.nim shaders/render2d.v.pica
##
##   -d:shadyNoPixie is recommended (not required): `toPica` needs no pixie, so
##   this skips compiling Shady's CPU-sim runtime. The output path defaults to
##   shaders/render2d.v.pica when omitted.

import shady, vmath
import std/os

# --- SOURCE OF TRUTH --------------------------------------------------------
# Canonical proc, taken verbatim from Shady's tests/test_pica.nim (the
# hardware-verified shader). Parameter ORDER is ABI-significant: Shady assigns
# vertex attribute registers v0/v1/v2 in declaration order, and the citro3d
# backend's AttrInfo loaders bind position->v0, uv->v1, color->v2.
proc render2dVert(
  gl_Position: var Vec4,
  projection: Uniform[Mat4],
  inPos: Vec2,
  inUv: Vec2,
  inColor: Vec4,
  outUv: var Vec2,
  outColor: var Vec4
) =
  gl_Position = projection * vec4(inPos.x, inPos.y, 0.0, 1.0)
  outUv = inUv
  # GPU_UNSIGNED_BYTE color is NOT normalized by the PICA200, so map [0,255] ->
  # [0,1] in-shader and clamp. If the backend ever switches v2 to GPU_FLOAT,
  # remove the /255 here (and in the proc) — colors would otherwise render dark.
  outColor = min(inColor * (1.0/255.0), vec4(1.0, 1.0, 1.0, 1.0))

const render2dPica = toPica(render2dVert)

# --- banner -----------------------------------------------------------------
# Prepended to Shady's output. Both this banner and Shady's own
# "; Generated by Shady toPica" header are picasso `;` comments, so they coexist.
# Preserves the ABI-contract documentation that lived in the hand-written file
# so the committed artifact stays self-describing.
const banner = """; render2d.v.pica — PICA200 vertex shader for UV-mapped 2D quads
;
; GENERATED FILE — DO NOT EDIT BY HAND.
; Source of truth: tools/gen_render2d_pica.nim (the `render2dVert` Nim proc).
; Regenerate with:
;   nim r -d:shadyNoPixie --path:"$HOME/git/shady/src" \
;     tools/gen_render2d_pica.nim shaders/render2d.v.pica
; Requires Shady's `toPica` (branch matt.spurlin/3ds-pica200-support).
; The exact Shady commit is recorded in the git commit that regenerated this
; file, not pinned in this banner (a literal here would silently go stale).
;
; Assembled by scripts/build_3ds.sh stage 1:
;   picasso shaders/render2d.v.pica -o build/render2d.shbin
;
; ABI contract the citro3d backend binds to (must not change):
;   Uniform by name : .fvec projection[4]  (dvleGetUniformRegister "projection")
;   Attribute order : v0 = position (GPU_FLOAT x2)
;                     v1 = uv       (GPU_FLOAT x2)
;                     v2 = color    (GPU_UNSIGNED_BYTE x4)
;   Output semantics: .out outpos position / outtc0 texcoord0 / outclr color
;   Color quirk     : GPU_UNSIGNED_BYTE is un-normalized on PICA200; the shader
;                     multiplies color by 1/255 and clamps to [0,1].
; Internal details (alias names, constant-pool names, register allocation) are
; chosen by Shady and are NOT part of the ABI.
;
"""

proc main() =
  let outPath =
    if paramCount() >= 1: paramStr(1)
    else: "shaders" / "render2d.v.pica"
  writeFile(outPath, banner & render2dPica)
  echo "Wrote ", outPath, " (", (banner.len + render2dPica.len), " bytes)"

when isMainModule:
  main()
